const ACTION_TYPES = {
  ADD_TO_SAVED_LOCATIONS: 'ADD_TO_SAVED_LOCATIONS',
  REMOVE_FROM_SAVED_LOCATIONS: 'REMOVE_FROM_SAVED_LOCATIONS',
  SET_WEATHER_INFO: 'SET_WEATHER_INFO',
};

export default ACTION_TYPES;